FROM golang:1.8

MAINTAINER Ye Zhang <zhangye.168@163.com>

RUN apt-get update \
    && apt-get install -y -q \
       gcc libc-dev \
       librados-dev \
       librbd-dev

COPY . /go/src/github.com/zh168654/docker-volume-rbd
WORKDIR /go/src/github.com/zh168654/docker-volume-rbd

RUN set -ex \
    && go install

CMD ["/go/bin/docker-volume-rbd"]
